// KeyedPose.idl
module docs_turtlesim {
    module msg {
        struct KeyedPose {
            @key long key;
            double x;
            double y;
            double theta;

            double linear_velocity;
            double angular_velocity;
        };
    };
};
