version: "3"

services:
  ros_talker:
    build:
      context: .
    command: >-
      sh -c "route del default &&
      route add default gw 10.1.1.1 eth0 &&
      ros2 run demo_nodes_cpp talker"
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      DISPLAY: ":1"
      FASTRTPS_DEFAULT_PROFILES_FILE: "node_configuration.xml"
      ROS_DISCOVERY_SERVER: "TCPv4:[10.1.1.1]:10111"
    cap_add:
      - ALL
    networks:
      - talker_net

  ros_listener:
    build:
      context: .
    command: >-
      sh -c "route del default &&
      route add default gw 10.2.1.1 eth0 &&
      ros2 run demo_nodes_cpp listener"
    cap_add:
      - ALL
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      DISPLAY: ":1"
      FASTRTPS_DEFAULT_PROFILES_FILE: "node_configuration.xml"
      ROS_DISCOVERY_SERVER: "TCPv4:[10.1.1.1]:10111"
    networks:
      - listener_net

  fast_dds_discovery_server:
    build:
      context: .
    command: sh -c "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
      iptables -A FORWARD -i eth0 -j ACCEPT &&
      iptables -A FORWARD -i eth1 -j ACCEPT &&
      iptables -A INPUT -i eth0 -j ACCEPT &&
      iptables -A INPUT -i eth1 -j ACCEPT &&
      iptables -A OUTPUT -j ACCEPT &&
      route del default &&
      route add default gw 10.3.2.1 eth1 &&
      fastdds discovery -i 0 -x server_configuration.xml"
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
    sysctls:
      - net.ipv4.conf.all.forwarding=1
      - net.ipv4.ip_forward=1

    networks:
      talker_net:
        ipv4_address: 10.1.1.1
      wan_net:
        ipv4_address: 10.3.1.1

  router:
    build:
      context: .
    command: sh -c "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
      iptables -A FORWARD -i eth0 -j ACCEPT &&
      iptables -A FORWARD -i eth1 -j ACCEPT &&
      iptables -A INPUT -i eth0 -j ACCEPT &&
      iptables -A INPUT -i eth1 -j ACCEPT &&
      iptables -A OUTPUT -j ACCEPT &&
      route del default &&
      route add default gw 10.3.1.1 eth1 &&
      sleep infinity"
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
    sysctls:
      - net.ipv4.conf.all.forwarding=1
      - net.ipv4.ip_forward=1

    networks:
      listener_net:
        ipv4_address: 10.2.1.1
      wan_net:
        ipv4_address: 10.3.2.1

networks:
  talker_net:
    name: talker_net
    external: true
  listener_net:
    name: listener_net
    external: true
  wan_net:
    name: wan_net
    external: true
