FROM ubuntu-vulcanexus-cloud:galactic

# Install demo-nodes-cpp
RUN source /opt/vulcanexus/galactic/setup.bash && \
    apt update && \
    apt install -y ros-galactic-demo-nodes-cpp

COPY ./run.bash /
RUN chmod +x /run.bash

# Setup entrypoint
ENTRYPOINT ["/run.bash"]
