FROM ubuntu-vulcanexus-cloud:humble

# Install demo-nodes-cpp
RUN source /opt/vulcanexus/humble/setup.bash && \
    apt update && \
    apt install -y ros-humble-demo-nodes-cpp

COPY ./run.bash /
RUN chmod +x /run.bash

# Setup entrypoint
ENTRYPOINT ["/run.bash"]
