FROM ubuntu-vulcanexus-cloud:kilted

# Install demo-nodes-cpp
RUN source /opt/vulcanexus/kilted/setup.bash && \
    apt update && \
    apt install -y ros-kilted-demo-nodes-cpp

COPY ./run.bash /
RUN chmod +x /run.bash

# Setup entrypoint
ENTRYPOINT ["/run.bash"]
