FROM ubuntu-vulcanexus-cloud:jazzy

# Install demo-nodes-cpp
RUN source /opt/vulcanexus/jazzy/setup.bash && \
    apt update && \
    apt install -y ros-jazzy-demo-nodes-cpp

COPY ./run.bash /
RUN chmod +x /run.bash

# Setup entrypoint
ENTRYPOINT ["/run.bash"]
