FROM ubuntu-vulcanexus-cloud:iron

# Install demo-nodes-cpp
RUN source /opt/vulcanexus/iron/setup.bash && \
    apt update && \
    apt install -y ros-iron-demo-nodes-cpp

COPY ./run.bash /
RUN chmod +x /run.bash

# Setup entrypoint
ENTRYPOINT ["/run.bash"]
