name: Install from binaries Ubuntu

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-install-from-binaries:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install from binaries
        run: |
          bash docs/resources/scripts/linux_binary_installation.bash
