name: Install from sources Ubuntu

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-install-from-sources:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros2_distro:
          - iron
          - humble

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ros2_distro }}
          submodules: 'recursive'

      - name: Install from sources
        run: |
          bash docs/resources/scripts/linux_source_installation.bash
